version: '3'

services:

  web:

    image: nginx
    ports:
    - "9092:80"
  database:

    image: mysql
    ports: 
    - "5555:3306"

volumes:
  - type: volume
    source: mydata
    target: /data
    volume:
    nocopy: true
  - type: bind
    source: ./static
    target: /opt/app/static

     

volumes:

  mydata:

